<?php
/**
 * NavinDBhudiya ProductRecommendation
 * Personalized Recommendations Template
 *
 * @var \NavinDBhudiya\ProductRecommendation\Block\Personalized\Recommendations $block
 */

$products = $block->getProducts();
if (empty($products)) {
    return;
}

$type = $block->getRecommendationType();
$title = $block->getTitle();
$imageHelper = $block->getImage($products[0] ?? null, 'category_page_grid');
?>

<div class="block block-personalized-recommendations block-<?= $block->escapeHtmlAttr($type) ?>"
     data-mage-init='{"NavinDBhudiya_ProductRecommendation/js/personalized-slider": {}}'>

    <div class="block-title title">
        <strong id="block-<?= $block->escapeHtmlAttr($type) ?>-heading" role="heading" aria-level="2">
            <span class="recommendation-icon <?= $block->escapeHtmlAttr($block->getIconClass()) ?>"></span>
            <?= $block->escapeHtml($title) ?>
        </strong>
    </div>

    <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($type) ?>-heading">
        <div class="products wrapper grid products-grid products-personalized">
            <ol class="products list items product-items">
                <?php foreach ($products as $product): ?>
                    <li class="item product product-item">
                        <div class="product-item-info" data-container="product-grid">
                            <?php
                            $productImage = $block->getImage($product, 'category_page_grid');
                            ?>
                            <a href="<?= $block->escapeUrl($block->getProductUrl($product)) ?>"
                               class="product photo product-item-photo"
                               tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>

                            <div class="product details product-item-details">
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= $block->escapeUrl($block->getProductUrl($product)) ?>">
                                        <?= $block->escapeHtml($product->getName()) ?>
                                    </a>
                                </strong>

                                <?= $block->getProductPrice($product) ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($product); ?>
                                                <?php if ($postParams): ?>
                                                <form data-role="tocart-form"
                                                      data-product-sku="<?= $block->escapeHtmlAttr($product->getSku()) ?>"
                                                      action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                      method="post">
                                                    <input type="hidden"
                                                           name="product"
                                                           value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                    <input type="hidden"
                                                           name="<?= /* @noEscape */
                                                           \Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED ?>"
                                                           value="<?= /* @noEscape */
                                                           $postParams['data'][\Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($product->isAvailable()): ?>
                                                    <div class="stock available">
                                                        <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                    </div>
                                                <?php else: ?>
                                                    <div class="stock unavailable">
                                                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>

                                        <div class="actions-secondary" data-role="add-to-links">
                                            <?php if ($block->getAddToWishlistParams($product)): ?>
                                                <a href="#"
                                                   class="action towishlist"
                                                   title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                                   aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                                   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($product) ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                </a>
                                            <?php endif; ?>

                                            <?php if ($block->getAddToCompareUrl()): ?>
                                                <a href="#"
                                                   class="action tocompare"
                                                   title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                   aria-label="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                   data-post='<?= /* @noEscape */ $block->getAddToCompareUrl() ?>'
                                                   role="button">
                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
</div>
